"""Tests for markdown report builder."""

from __future__ import annotations

from ydbdoc_review.config.loader import load_config
from ydbdoc_review.llm.usage import LLMUsage, UsageTracker
from ydbdoc_review.pipeline.analyze import PairPlan
from ydbdoc_review.pipeline.pairs import DocPair
from ydbdoc_review.pipeline.types import FileTranslationResult, PRTranslationResult, PairRunResult
from ydbdoc_review.reporting.builder import (
    ReportMeta,
    build_commit_message,
    build_full_report,
    build_source_pr_comment,
)
from ydbdoc_review.translation.glossary import load_glossary
from ydbdoc_review.translation.schemas import CriticIssueOut


def _cfg():
    return load_config(env={"YDBDOC_YC_FOLDER_ID": "b1", "YDBDOC_YC_API_KEY": "k"})


def _sample_result(*, new_file: bool = False) -> PRTranslationResult:
    pair = DocPair(
        ru_path="ydb/docs/ru/a.md",
        en_path="ydb/docs/en/a.md",
        ru_changed=True,
    )
    summary = "EN missing — generate from RU" if new_file else "RU changed, EN unchanged"
    plan = PairPlan(
        pair=pair,
        action="translate_to_en",
        source_path=pair.ru_path,
        target_path=pair.en_path,
        source_lang="ru",
        target_lang="en",
        summary=summary,
    )
    issue = CriticIssueOut(
        segment_id="s0042",
        severity="warning",
        category="terminology",
        comment='"command" → "директива"',
        suggested_text="directive",
    )
    fr = FileTranslationResult(
        file_path=pair.en_path,
        final_text="Hello",
        segments_count=12,
        verdict="warnings",
        prompt_version="v1",
        input_tokens=100,
        output_tokens=50,
        estimated_cost_usd=0.01,
        models_used=["yandexgpt-5.1"],
        critic_applied=[issue],
        heuristic_warnings=["cyrillic_in_en: 1 occurrence at line 87"],
    )
    return PRTranslationResult(
        pair_results=[
            PairRunResult(plan=plan, target_text="Hello", file_result=fr),
        ]
    )


def test_build_source_pr_comment_new_and_updated():
    cfg = _cfg()
    body = build_source_pr_comment(
        _sample_result(new_file=True),
        translation_pr_number=99,
        meta=ReportMeta(mode="doc_translate", report_number=1, elapsed_s=134),
        config=cfg,
    )
    assert "1 (1 новых)" in body
    assert "Translation PR | #99" in body


def test_build_full_report_sections():
    cfg = _cfg()
    usage = UsageTracker()
    usage.add(LLMUsage("yandexgpt-5.1", 12341, 4102, 100.0, 1, True, role="translate"))
    usage.add(LLMUsage("qwen3.6-35b-a3b", 8221, 1503, 80.0, 0, True, role="critic"))

    body = build_full_report(
        _sample_result(),
        meta=ReportMeta(mode="doc_translate", report_number=1, elapsed_s=90),
        config=cfg,
        usage=usage,
        glossary=load_glossary(),
    )
    assert "отчёт #1" in body
    assert "Сегментов переведено: 12" in body
    assert "translator 12,341/4,102" in body
    assert "critic 8,221/1,503" in body
    assert "Retry total: 1" in body
    assert "Heuristic warnings" in body
    assert "s0042" in body
    assert "Glossary used" in body
    assert "Prompt version: v1" in body
    assert "Generated by ydbdoc-review" in body


def test_build_full_report_error_and_deleted_rows():
    cfg = _cfg()
    pair = DocPair(
        ru_path="ydb/docs/ru/x.md",
        en_path="ydb/docs/en/x.md",
        ru_deleted=True,
        ru_changed=True,
    )
    del_plan = PairPlan(
        pair=pair,
        action="delete_en",
        source_path=pair.ru_path,
        target_path=pair.en_path,
        source_lang="ru",
        target_lang="en",
    )
    err_pair = DocPair(
        ru_path="ydb/docs/ru/e.md",
        en_path="ydb/docs/en/e.md",
        ru_changed=True,
    )
    err_plan = PairPlan(
        pair=err_pair,
        action="translate_to_en",
        source_path=err_pair.ru_path,
        target_path=err_pair.en_path,
        source_lang="ru",
        target_lang="en",
    )
    result = PRTranslationResult(
        pair_results=[
            PairRunResult(plan=del_plan, deleted=True),
            PairRunResult(plan=err_plan, error="API down"),
        ]
    )
    body = build_full_report(
        result,
        meta=ReportMeta(mode="doc_verify", report_number=2, elapsed_s=5),
        config=cfg,
    )
    assert "deleted" in body
    assert "error" in body


def test_build_commit_message():
    cfg = _cfg()
    msg = build_commit_message(12, _sample_result(), config=cfg)
    assert "PR #12" in msg
    verify_msg = build_commit_message(12, _sample_result(), config=cfg, verify=True)
    assert "doc_verify" in verify_msg
