"""Tests for markdown report builder."""

from __future__ import annotations

from ydbdoc_review.config.loader import load_config
from ydbdoc_review.pipeline.analyze import PairPlan
from ydbdoc_review.pipeline.pairs import DocPair
from ydbdoc_review.pipeline.types import FileTranslationResult, PRTranslationResult, PairRunResult
from ydbdoc_review.reporting.builder import (
    ReportMeta,
    build_commit_message,
    build_full_report,
    build_source_pr_comment,
)
from ydbdoc_review.translation.schemas import CriticIssueOut, CriticResponse


def _cfg():
    return load_config(env={"YDBDOC_YC_FOLDER_ID": "b1", "YDBDOC_YC_API_KEY": "k"})


def _sample_result(*, new_file: bool = False) -> PRTranslationResult:
    pair = DocPair(
        ru_path="ydb/docs/ru/a.md",
        en_path="ydb/docs/en/a.md",
        ru_changed=True,
    )
    summary = "EN missing — generate from RU" if new_file else "RU changed, EN unchanged"
    plan = PairPlan(
        pair=pair,
        action="translate_to_en",
        source_path=pair.ru_path,
        target_path=pair.en_path,
        source_lang="ru",
        target_lang="en",
        summary=summary,
    )
    unresolved = CriticIssueOut(
        segment_id="s0042",
        severity="warning",
        category="terminology",
        comment='использовано "string table" вместо "row table"',
        suggested_text="row table",
    )
    fr = FileTranslationResult(
        file_path=pair.en_path,
        final_text="Hello",
        segments_count=12,
        verdict="warnings",
        prompt_version="v1",
        critic_applied=[
            CriticIssueOut(
                segment_id="s0001",
                severity="warning",
                category="formatting",
                comment="fixed spacing",
                suggested_text="fixed",
            )
        ],
        critic_unresolved=CriticResponse(verdict="warnings", issues=[unresolved]),
        heuristic_warnings=["Кириллица в EN-тексте (строка ~5): «командой YQL»"],
        segment_locations={"s0042": "Overview"},
    )
    return PRTranslationResult(
        pair_results=[
            PairRunResult(plan=plan, target_text="Hello", file_result=fr),
        ]
    )


def test_build_source_pr_comment_new_and_updated():
    cfg = _cfg()
    body = build_source_pr_comment(
        _sample_result(new_file=True),
        translation_pr_number=99,
        meta=ReportMeta(mode="doc_translate", report_number=1, elapsed_s=134),
        config=cfg,
    )
    assert "1 (1 новых)" in body
    assert "Translation PR | #99" in body
    assert "требует правок" in body
    assert "Сегментов" not in body


def test_build_full_report_reviewer_focused():
    cfg = _cfg()
    body = build_full_report(
        _sample_result(),
        meta=ReportMeta(mode="doc_translate", report_number=1, elapsed_s=90),
        config=cfg,
    )
    assert "Рекомендация:" in body
    assert "Что исправить" in body
    assert "Overview (`s0042`)" in body
    assert "string table" in body
    assert "💡 Совет: row table" in body
    assert "Кириллица в EN-тексте" in body
    assert "fixed spacing" not in body
    assert "Сегментов переведено" not in body
    assert "Critic fixes auto-applied" not in body
    assert "Glossary used" not in body
    assert "Generated by ydbdoc-review" in body


def test_build_full_report_error_and_deleted_rows():
    cfg = _cfg()
    pair = DocPair(
        ru_path="ydb/docs/ru/x.md",
        en_path="ydb/docs/en/x.md",
        ru_deleted=True,
        ru_changed=True,
    )
    del_plan = PairPlan(
        pair=pair,
        action="delete_en",
        source_path=pair.ru_path,
        target_path=pair.en_path,
        source_lang="ru",
        target_lang="en",
    )
    err_pair = DocPair(
        ru_path="ydb/docs/ru/e.md",
        en_path="ydb/docs/en/e.md",
        ru_changed=True,
    )
    err_plan = PairPlan(
        pair=err_pair,
        action="translate_to_en",
        source_path=err_pair.ru_path,
        target_path=err_pair.en_path,
        source_lang="ru",
        target_lang="en",
    )
    result = PRTranslationResult(
        pair_results=[
            PairRunResult(plan=del_plan, deleted=True),
            PairRunResult(plan=err_plan, error="API down"),
        ]
    )
    body = build_full_report(
        result,
        meta=ReportMeta(mode="doc_verify", report_number=2, elapsed_s=5),
        config=cfg,
    )
    assert "Ошибки pipeline" in body
    assert "API down" in body


def test_build_full_report_all_ok():
    cfg = _cfg()
    pair = DocPair(
        ru_path="ydb/docs/ru/a.md",
        en_path="ydb/docs/en/a.md",
        ru_changed=True,
    )
    plan = PairPlan(
        pair=pair,
        action="translate_to_en",
        source_path=pair.ru_path,
        target_path=pair.en_path,
        source_lang="ru",
        target_lang="en",
    )
    fr = FileTranslationResult(
        file_path=pair.en_path,
        final_text="Hello",
        segments_count=1,
        verdict="ok",
        prompt_version="v1",
    )
    body = build_full_report(
        PRTranslationResult(pair_results=[PairRunResult(plan=plan, file_result=fr)]),
        meta=ReportMeta(mode="doc_translate", report_number=1, elapsed_s=1),
        config=cfg,
    )
    assert "можно мержить" in body
    assert "открытых замечаний нет" in body


def test_build_commit_message():
    cfg = _cfg()
    msg = build_commit_message(12, _sample_result(), config=cfg)
    assert "PR #12" in msg
    verify_msg = build_commit_message(12, _sample_result(), config=cfg, verify=True)
    assert "doc_verify" in verify_msg
